<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class Kategori extends Seeder
{
    public function run()
    {
        $data = [

            [
                'id_kategori' => 1,
                'nama_kategori' => 'Kimchi & Makanan Pendamping',
                'deskripsi'    => 'Lorem',
                'slug'    => 'kimchi-dan-makanan-pendamping',
                'img'    => 'ICON CATEGORY-01.png',
                'short' => 1,
            ],
            [
                'id_kategori' => 2,
                'nama_kategori' => 'Nori',
                'deskripsi'    => 'Lorem',
                'slug'    => 'nori',
                'img'    => 'ICON CATEGORY-02.png',
                'short' => 2,
            ],
            [
                'id_kategori' => 3,
                'nama_kategori' => 'Buah & Sayur',
                'deskripsi'    => 'Lorem',
                'slug'    => 'buah-dan-sayur',
                'img'    => 'ICON CATEGORY-03.png',
                'short' => 3,
            ],
            [
                'id_kategori' => 4,
                'nama_kategori' => 'Saus & Bubuk Cabai',
                'deskripsi'    => 'Lorem',
                'slug'    => 'saus-dan-bubuk-cabai',
                'img'    => 'ICON CATEGORY-04.png',
                'short' => 4,
            ],
            [
                'id_kategori' => 5,
                'nama_kategori' => 'Daging & Telur',
                'deskripsi'    => 'Lorem',
                'slug'    => 'daging-dan-telur',
                'img'    => 'ICON CATEGORY-05.png',
                'short' => 5,
            ],
            [
                'id_kategori' => 6,
                'nama_kategori' => 'Makanan Laut',
                'deskripsi'    => 'Lorem',
                'slug'    => 'makanan-laut',
                'img'    => 'ICON CATEGORY-06.png',
                'short' => 6,
            ],
            [
                'id_kategori' => 7,
                'nama_kategori' => 'Beras & kacang',
                'deskripsi'    => 'Lorem',
                'slug'    => 'beras-dan-kacang',
                'img'    => 'ICON CATEGORY-07.png',
                'short' => 7,
            ],
            [
                'id_kategori' => 8,
                'nama_kategori' => 'Ramen',
                'deskripsi'    => 'Lorem',
                'slug'    => 'ramen',
                'img'    => 'ICON CATEGORY-08.png',
                'short' => 8,
            ],
            [
                'id_kategori' => 9,
                'nama_kategori' => 'Snack',
                'deskripsi'    => 'Lorem',
                'slug'    => 'snack',
                'img'    => 'ICON CATEGORY-09.png',
                'short' => 9,
            ],
            [
                'id_kategori' => 10,
                'nama_kategori' => 'Roti',
                'deskripsi'    => 'Lorem',
                'slug'    => 'roti',
                'img'    => 'ICON CATEGORY-10.png',
                'short' => 10,
            ],
            [
                'id_kategori' => 11,
                'nama_kategori' => 'Susu & Olahan',
                'deskripsi'    => 'Lorem',
                'slug'    => 'susu-dan-olahan',
                'img'    => 'ICON CATEGORY-11.png',
                'short' => 12,
            ],
            [
                'id_kategori' => 12,
                'nama_kategori' => 'Minyak',
                'deskripsi'    => 'Lorem',
                'slug'    => 'minyak',
                'img'    => 'ICON CATEGORY-12.png',
                'short' => 13,
            ],
            [
                'id_kategori' => 13,
                'nama_kategori' => 'Minuman Kopi & Teh',
                'deskripsi'    => 'Lorem',
                'slug'    => 'minuman-kopi-dan-teh',
                'img'    => 'ICON CATEGORY-13.png',
                'short' => 14,
            ],
            [
                'id_kategori' => 14,
                'nama_kategori' => 'Dumpling & Makanan Beku',
                'deskripsi'    => 'Lorem',
                'slug'    => 'dumpling-dan-makanan-beku',
                'img'    => 'ICON CATEGORY-14.png',
                'short' => 15,
            ],
            [
                'id_kategori' => 15,
                'nama_kategori' => 'Kosmetik',
                'deskripsi'    => 'Lorem',
                'slug'    => 'kosmetik',
                'img'    => 'ICON CATEGORY-15.png',
                'short' => 16,
            ],
            [
                'id_kategori' => 16,
                'nama_kategori' => 'Peralatan Dapur',
                'deskripsi'    => 'Lorem',
                'slug'    => 'peralatan-dapur',
                'img'    => 'ICON CATEGORY-16.png',
                'short' => 17,
            ],
            [
                'id_kategori' => 17,
                'nama_kategori' => 'Sup',
                'deskripsi'    => 'Lorem',
                'slug'    => 'sup',
                'img'    => 'ICON CATEGORY-17.png',
                'short' => 18,
            ],
            [
                'id_kategori' => 18,
                'nama_kategori' => 'Nasi Instant & Bubur',
                'deskripsi'    => 'Lorem',
                'slug'    => 'nasi-instant-dan-bubur',
                'img'    => 'ICON CATEGORY-18.png',
                'short' => 11,
            ]
        ];

        $this->db->table('jsf_kategori')->insertBatch($data);

        $data2 = [

            [
                'id_kategori' => 1,
                'id_sub_kategori' => 1,
                'nama_kategori' => '김치 / KIMCHI',
                'deskripsi'    => 'Lorem',
                'slug'    => '김치-kimchi',
            ],
            [
                'id_kategori' => 1,
                'id_sub_kategori' => 2,
                'nama_kategori' => '반찬 / MAKANAN PENDAMPING',
                'deskripsi'    => 'Lorem',
                'slug'    => '반찬-makanan-pendamping',
            ],

            [
                'id_kategori' => 2,
                'id_sub_kategori' => 3,
                'nama_kategori' => '김 / NORI',
                'deskripsi'    => 'Lorem',
                'slug'    => '김-nori',
            ],

            [
                'id_kategori' => 2,
                'id_sub_kategori' => 4,
                'nama_kategori' => '김밥 김 / KIMBAB KIM',
                'deskripsi'    => 'Lorem',
                'slug'    => '김밥-김-kimbab-kim',
            ],
            [
                'id_kategori' => 3,
                'id_sub_kategori' => 5,
                'nama_kategori' => '과일 / BUAH',
                'deskripsi'    => 'Lorem',
                'slug'    => '과일-buah',
            ],
            [
                'id_kategori' => 3,
                'id_sub_kategori' => 6,
                'nama_kategori' => '채소 / SAYUR',
                'deskripsi'    => 'Lorem',
                'slug'    => '채소-sayur',
            ],
            [
                'id_kategori' => 4,
                'id_sub_kategori' => 7,
                'nama_kategori' => '한국 소스 / SAUS KOREA',
                'deskripsi'    => 'Lorem',
                'slug'    => '한국-소스-saus-korea',
            ],
            [
                'id_kategori' => 4,
                'id_sub_kategori' => 8,
                'nama_kategori' => '소스 / SAUS',
                'deskripsi'    => 'Lorem',
                'slug'    => '소스-saus',
            ],
            [
                'id_kategori' => 4,
                'id_sub_kategori' => 9,
                'nama_kategori' => '조미료 / BUBUK CABAI',
                'deskripsi'    => 'Lorem',
                'slug'    => '조미료-bubuk-cabai',
            ],

            [
                'id_kategori' => 5,
                'id_sub_kategori' => 10,
                'nama_kategori' => '소고기 / DAGING SAPI',
                'deskripsi'    => 'Lorem',
                'slug'    => '소고기-daging-sapi',
            ],
            [
                'id_kategori' => 5,
                'id_sub_kategori' => 11,
                'nama_kategori' => '돼지고기 / DAGING BABI',
                'deskripsi'    => 'Lorem',
                'slug'    => '돼지고기-daging-babi',
            ],
            [
                'id_kategori' => 5,
                'id_sub_kategori' => 12,
                'nama_kategori' => '닭고기 / DAGING AYAM',
                'deskripsi'    => 'Lorem',
                'slug'    => '닭고기-daging-ayam',
            ],
            [
                'id_kategori' => 5,
                'id_sub_kategori' => 13,
                'nama_kategori' => '계란 / TELUR',
                'deskripsi'    => 'Lorem',
                'slug'    => '계란-telur',
            ],

            [
                'id_kategori' => 6,
                'id_sub_kategori' => 14,
                'nama_kategori' => '생선 / IKAN',
                'deskripsi'    => 'Lorem',
                'slug'    => '생선-ikan',
            ],

            [
                'id_kategori' => 6,
                'id_sub_kategori' => 15,
                'nama_kategori' => '오징어 / CUMI',
                'deskripsi'    => 'Lorem',
                'slug'    => '오징어-cumi',
            ],

            [
                'id_kategori' => 6,
                'id_sub_kategori' => 16,
                'nama_kategori' => '조개 / KERANG',
                'deskripsi'    => 'Lorem',
                'slug'    => '조개-kerang',
            ],

            [
                'id_kategori' => 7,
                'id_sub_kategori' => 17,
                'nama_kategori' => '쌀 / BERAS',
                'deskripsi'    => 'Lorem',
                'slug'    => '쌀-beras',
            ],
            [
                'id_kategori' => 7,
                'id_sub_kategori' => 18,
                'nama_kategori' => '잡곡 / BULIR',
                'deskripsi'    => 'Lorem',
                'slug'    => '잡곡-bulir',
            ],
            [
                'id_kategori' => 7,
                'id_sub_kategori' => 19,
                'nama_kategori' => '견과 / KACANG',
                'deskripsi'    => 'Lorem',
                'slug'    => '견과-kacang',
            ],
            [
                'id_kategori' => 8,
                'id_sub_kategori' => 20,
                'nama_kategori' => '국물 라면 / RAMEN KUAH',
                'deskripsi'    => 'Lorem',
                'slug'    => '국물-라면-ramen-kuah',
            ],
            [
                'id_kategori' => 8,
                'id_sub_kategori' => 21,
                'nama_kategori' => '볶음 라면 / RAMEN GORENG',
                'deskripsi'    => 'Lorem',
                'slug'    => '볶음-라면-ramen-goreng',
            ],

            [
                'id_kategori' => 9,
                'id_sub_kategori' => 22,
                'nama_kategori' => '비스킷 / BISKUIT',
                'deskripsi'    => 'Lorem',
                'slug'    => '비스킷-biskuit',
            ],
            [
                'id_kategori' => 9,
                'id_sub_kategori' => 23,
                'nama_kategori' => '쿠키 / COOKIE',
                'deskripsi'    => 'Lorem',
                'slug'    => '쿠키-cookie',
            ],
            [
                'id_kategori' => 9,
                'id_sub_kategori' => 24,
                'nama_kategori' => '파이 / PIE',
                'deskripsi'    => 'Lorem',
                'slug'    => '파이-pie',
            ],

            [
                'id_kategori' => 10,
                'id_sub_kategori' => 25,
                'nama_kategori' => '식빵 / ROTI TAWAR',
                'deskripsi'    => 'Lorem',
                'slug'    => '빵-roti-tawar',
            ],

            [
                'id_kategori' => 10,
                'id_sub_kategori' => 26,
                'nama_kategori' => '빵 / ROTI BIASA',
                'deskripsi'    => 'Lorem',
                'slug'    => '빵-roti-biasa',
            ],
            [
                'id_kategori' => 11,
                'id_sub_kategori' => 27,
                'nama_kategori' => '우유 / SUSU',
                'deskripsi'    => 'Lorem',
                'slug'    => '우유-susu',
            ],
            [
                'id_kategori' => 11,
                'id_sub_kategori' => 28,
                'nama_kategori' => '두유 / SUSU KEDELAI',
                'deskripsi'    => 'Lorem',
                'slug'    => '두유-susu-kedelai',
            ],
            [
                'id_kategori' => 11,
                'id_sub_kategori' => 29,
                'nama_kategori' => '치즈 / KEJU',
                'deskripsi'    => 'Lorem',
                'slug'    => '치즈-keju',
            ],
            [
                'id_kategori' => 12,
                'id_sub_kategori' => 30,
                'nama_kategori' => '튀김용 / UNTUK GORENGAN',
                'deskripsi'    => 'Lorem',
                'slug'    => '튀김용-untuk-gorengan',
            ],
            [
                'id_kategori' => 12,
                'id_sub_kategori' => 31,
                'nama_kategori' => '요리용 / UNTUK MASAKAN',
                'deskripsi'    => 'Lorem',
                'slug'    => '요리용-untuk-masakan',
            ],
            [
                'id_kategori' => 12,
                'id_sub_kategori' => 32,
                'nama_kategori' => '건강용 / UNTUK SEHAT',
                'deskripsi'    => 'Lorem',
                'slug'    => '건강용-untuk-sehat',
            ],
            [
                'id_kategori' => 13,
                'id_sub_kategori' => 33,
                'nama_kategori' => '음료 / MINUMAN',
                'deskripsi'    => 'Lorem',
                'slug'    => '음료-minuman',
            ],
            [
                'id_kategori' => 13,
                'id_sub_kategori' => 34,
                'nama_kategori' => '커피 / KOPI',
                'deskripsi'    => 'Lorem',
                'slug'    => '커피-kopi',
            ],
            [
                'id_kategori' => 13,
                'id_sub_kategori' => 35,
                'nama_kategori' => '차 / TEH',
                'deskripsi'    => 'Lorem',
                'slug'    => '차-teh',
            ],
            [
                'id_kategori' => 14,
                'id_sub_kategori' => 36,
                'nama_kategori' => '만두 / DUMPLING',
                'deskripsi'    => 'Lorem',
                'slug'    => '만두-dumpling',
            ],
            [
                'id_kategori' => 14,
                'id_sub_kategori' => 37,
                'nama_kategori' => '냉동식품 / MAKANAN BEKU',
                'deskripsi'    => 'Lorem',
                'slug'    => '냉동식품-makanan-beku',
            ],
            [
                'id_kategori' => 15,
                'id_sub_kategori' => 38,
                'nama_kategori' => '샴푸 / SHAMPOO',
                'deskripsi'    => 'Lorem',
                'slug'    => '샴푸-shampoo',
            ],
            [
                'id_kategori' => 15,
                'id_sub_kategori' => 39,
                'nama_kategori' => '비누 / SABUN',
                'deskripsi'    => 'Lorem',
                'slug'    => '비누-sabun',
            ],
            [
                'id_kategori' => 15,
                'id_sub_kategori' => 40,
                'nama_kategori' => '칫솔, 치약 / SIKAT GIGI, PASTA GIGI',
                'deskripsi'    => 'Lorem',
                'slug'    => '칫솔-치약-sikat-gigi-pasta-gigi',
            ],

            [
                'id_kategori' => 16,
                'id_sub_kategori' => 41,
                'nama_kategori' => '밀폐용기 / KONTAINER',
                'deskripsi'    => 'Lorem',
                'slug'    => '밀폐용기-kontainer',
            ],
            [
                'id_kategori' => 16,
                'id_sub_kategori' => 42,
                'nama_kategori' => '팬 / PANCI',
                'deskripsi'    => 'Lorem',
                'slug'    => '팬-panci',
            ],
            [
                'id_kategori' => 16,
                'id_sub_kategori' => 43,
                'nama_kategori' => '뚝배기 / MANGKUK KERAMIK',
                'deskripsi'    => 'Lorem',
                'slug'    => '뚝배기-mangkuk-keramik',
            ],
            [
                'id_kategori' => 18,
                'id_sub_kategori' => 44,
                'nama_kategori' => '즉석밥 / NASI INSTAN',
                'deskripsi'    => 'Lorem',
                'slug'    => '즉석밥-nasi-instan',
            ],
            [
                'id_kategori' => 18,
                'id_sub_kategori' => 45,
                'nama_kategori' => '죽 / BUBUR',
                'deskripsi'    => 'Lorem',
                'slug'    => '죽-bubur',
            ],
            [
                'id_kategori' => 8,
                'id_sub_kategori' => 46,
                'nama_kategori' => '국수 / NOODLE',
                'deskripsi'    => 'Lorem',
                'slug'    => '국수-noodle',
            ],
            [
                'id_kategori' => 17,
                'id_sub_kategori' => 47,
                'nama_kategori' => '액상 / SUP',
                'deskripsi'    => 'Lorem',
                'slug'    => '액상-sup',
            ],
            [
                'id_kategori' => 17,
                'id_sub_kategori' => 48,
                'nama_kategori' => '분말 / BUBUK',
                'deskripsi'    => 'Lorem',
                'slug'    => '분말-bubuk',
            ],
            [
                'id_kategori' => 17,
                'id_sub_kategori' => 49,
                'nama_kategori' => '재료 / BAHAN',
                'deskripsi'    => 'Lorem',
                'slug'    => '재료-bahan',
            ],
            [
                'id_kategori' => 10,
                'id_sub_kategori' => 50,
                'nama_kategori' => '믹스 / MIX',
                'deskripsi'    => 'Lorem',
                'slug'    => '믹스-mix',
            ],
            [
                'id_kategori' => 2,
                'id_sub_kategori' => 51,
                'nama_kategori' => '김스낵 / NORI SNACK',
                'deskripsi'    => 'Lorem',
                'slug'    => '김스낵-nori-snack',
            ],
            [
                'id_kategori' => 4,
                'id_sub_kategori' => 52,
                'nama_kategori' => '믹스 / MIX',
                'deskripsi'    => 'Lorem',
                'slug'    => '믹스-mix',
            ],
            [
                'id_kategori' => 4,
                'id_sub_kategori' => 53,
                'nama_kategori' => '소금 & 설탕 /GARAM & GULA',
                'deskripsi'    => 'Lorem',
                'slug'    => '소금-설탕-garam-gula',
            ],
            [
                'id_kategori' => 2,
                'id_sub_kategori' => 54,
                'nama_kategori' => '미역 / RUMPUT LAUT',
                'deskripsi'    => 'Lorem',
                'slug'    => '미역-rumput-laut',
            ],
            [
                'id_kategori' => 6,
                'id_sub_kategori' => 55,
                'nama_kategori' => '건어물 / KERING MAKANAN LAUT',
                'deskripsi'    => 'Lorem',
                'slug'    => '건어물-kering-makanan-laut',
            ]
        ];

        $this->db->table('jsf_sub_kategori')->insertBatch($data2);
    }
}
