name: Deploy to Share Hosting

on:
  push:
    branches:
      - develop

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          key_path: ${{ secrets.DEV_SSH_PATH }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            eval $(ssh-agent)
            ssh-add ${{ secrets.DEV_SSH_PATH }}
            ${{ secrets.DEV_CD }}
            git pull
            git status
            cp -rf ~/master/devStack/ssayomart-app/public/assets/* ~/public_html/public-dev.ssayomart.com/assets/
            ssh-agent -k
